### ISSUE TITLE
Allow Esc key press to close the context menu

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#35] opened 2021-12-16 11:35 UTC
The context menu does not close when the user hits the escape key. If the user does not want to select an option from the menu they must click outside the menu to get rid of the menu, and may inadvertently change something in the process (for example clicking on another column and changing the sort).

I would like the escape key to close the context menu, just as the escape key can be used to close browser context menus.

**Comment by nkappler** [comment] 2021-12-20 19:15
duplicate of #32

**Closed** 2022-06-14 15:30 UTC
Labels: duplicate, enhancement
