### ISSUE TITLE
Position Calculation is wrong when body has css transform bug (2)

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#39] opened 2022-07-12 14:25 UTC
The x,y positions are not calculated correctly when a transform e.g. scale(6.9) or similar is applied.

Check out this [demo](https://test.nubuilder.cloud/index.php?f=618b6d9e9485c80&r=-1&h=nuhome&u=test&p=nutest) and do a single tap on a "test" button.

Also open the link on a mobile phone and you'll see that the ctxmenu appears much further below on the screen.

**Comment by smalos** [comment] 2022-07-13 14:25
If there is no simple fix, a way to display the menu at a specific position X,Y would also be desirable.

**Comment by smalos** [comment] 2022-07-13 16:35
Thanks for your response and your efforts!

**Comment by nkappler** [comment] 2022-07-13 21:37
You're welcome!
You can track the progress on the [position](https://github.com/nkappler/ctxmenu/tree/position) branch. I've started to extract all positioning code into it's own file. Also, I noticed that the context menu can be outside the viewport, when the body is larger than the viewport. Probably it is easier to rewrite the positioning logic entirely, as it has grown into quite a mess and there are several changes required for the fixes.
Currently the code on the branch isn't working any better, but I'll let you know once I have done some fixes.
I'd appreciate your help validating the changes, once I feel they are ready... You seem to have a talent for finding peculiar bugs :joy:

**Comment by nkappler** [comment] 2022-07-13 21:41
>a way to display the menu at a specific position X,Y would also be desirable.

good point, will definitely add this as a convenience method.

**Comment by smalos** [comment] 2022-07-14 06:10
This sounds like a plan! I will occasionally pop in to check the progress and will help with testing once it's ready.

**Comment by nkappler** [comment] 2022-07-15 11:02
I've just uploaded another change and also pushed the compiled js files so you can download them from the `position` branch.
I've tried different transforms: scale > 1, scale < 1, scale and transform and all the former while zooming into the page and scrolling and I couldn't get the menu to render outside the viewport. To me the implementation seems very solid, but maybe you can break it 😅
Surprisingly to me, even 3D transforms work sufficiently well in my opinion, although not perfect in edge cases (pun intended 😄)

Thanks for reporting, I enjoy a good challenge and this certainly has been one so far!

**Comment by nkappler** [comment] 2022-07-15 11:12
I've created PR #40 and will merge it if you don't find more bugs

**Comment by smalos** [comment] 2022-07-15 13:29
Something seems wrong.  The menu appears at the very bottom of [this page](https://test.nubuilder.cloud/index.php?f=62d16a87e349c36&r=-1&u=test&p=nutest). Right-click the "test" button.

**Comment by nkappler** [comment] 2022-07-15 13:34
could you please use the non-minified version so I can debug the page and see what's going on?

**Comment by nkappler** [comment] 2022-07-15 14:48
I have just pushed some more fixes, I am pretty confident that it works as intended now 😄

**Comment by nkappler** [comment] 2022-07-15 15:50
I just pushed a fix for the box sizing issue, too.

**Closed** 2022-07-15 15:52 UTC

**Comment by smalos** [comment] 2022-07-15 15:56
Excellent, I'll test it a bit later today but think it's all good now.

**Comment by smalos** [comment] 2022-07-16 20:10
Thanks, it's perfect now.

**Comment by nkappler** [comment] 2022-07-16 20:52
Glad to hear that 🙂
