### ISSUE TITLE
Last menu item apepars off screen

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#25] opened 2021-08-19 14:41 UTC
The last menu item with text "e.g. Cursor Position: X:184 / Y:850" appears off screen when the context menu is opened the first time.
When the menu is opened again, the item is visible (the context menu top position is further up).

![last_item](https://user-images.githubusercontent.com/45562597/130088134-1a4d18d0-0e78-47c4-8ac5-cedf6937e104.jpg)

**Comment by nkappler** [comment] 2021-08-19 14:56
Thanks, I don't really consider this a bug.
The issue is the image (2nd item under Custom Elements):
When the menu renders the first time, the image isn't loaded yet and thus the height calculation is a bit off.
This can be fixed by setting the height attribute of the image. I'll fix the docs once I've finished releasing 1.3

Thanks for your continuous feedback!

**Closed** 2021-08-19 15:19 UTC
